spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/watchlist1?userLegacyDatetimeCode=false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8000

security:
  jwt:
    secret: development-key
    lifetime: 7200000 # 5 days